name: plcart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  auto_injector: 
    git: 
      url: git@github.com:AndreiLosev/auto_injector.git
      ref: get_by_className
  hive: ^2.2.3
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
